### PR TITLE
std::round is not defined in some platforms

### PR DESCRIPTION
**Pull request by tmpsantos**
Use the C version.

### CODE REVIEW

**Comment by springmeyer** [comment]
Which platforms? Can a compiler error be triggered on travis using some compiler combination?

**Comment by tmpsantos** [comment]
@springmeyer Android + GCC

**Comment by tmpsantos** [comment]
A bit more context, this is needed to have the latest Mapbox GL Native version building on the Qt CI. We did for a few other deps like in here, but I overlooked `vector-tile` https://github.com/mapbox/mason/pull/460

**Comment by springmeyer** [comment]
👌

**Pull request merged**
